# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1074, 734)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pwm3View = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pwm3View.sizePolicy().hasHeightForWidth())
        self.pwm3View.setSizePolicy(sizePolicy)
        self.pwm3View.setObjectName("pwm3View")
        self.verticalLayout_3.addWidget(self.pwm3View)
        self.gridLayout.addLayout(self.verticalLayout_3, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pwm1View = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pwm1View.sizePolicy().hasHeightForWidth())
        self.pwm1View.setSizePolicy(sizePolicy)
        self.pwm1View.setObjectName("pwm1View")
        self.verticalLayout.addWidget(self.pwm1View)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pwm2View = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pwm2View.sizePolicy().hasHeightForWidth())
        self.pwm2View.setSizePolicy(sizePolicy)
        self.pwm2View.setObjectName("pwm2View")
        self.verticalLayout_2.addWidget(self.pwm2View)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox.setBaseSize(QtCore.QSize(0, 105))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 60, 49, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 49, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 49, 16))
        self.label_3.setObjectName("label_3")
        self.edit_duty1 = QtWidgets.QLineEdit(self.groupBox)
        self.edit_duty1.setGeometry(QtCore.QRect(70, 60, 71, 21))
        self.edit_duty1.setObjectName("edit_duty1")
        self.sl_pwm1 = QtWidgets.QSlider(self.groupBox)
        self.sl_pwm1.setGeometry(QtCore.QRect(210, 60, 160, 20))
        self.sl_pwm1.setMaximum(100)
        self.sl_pwm1.setOrientation(QtCore.Qt.Horizontal)
        self.sl_pwm1.setObjectName("sl_pwm1")
        self.pb_Test = QtWidgets.QPushButton(self.groupBox)
        self.pb_Test.setGeometry(QtCore.QRect(960, 80, 84, 21))
        self.pb_Test.setObjectName("pb_Test")
        self.sl_pwm3 = QtWidgets.QSlider(self.groupBox)
        self.sl_pwm3.setGeometry(QtCore.QRect(210, 120, 160, 20))
        self.sl_pwm3.setOrientation(QtCore.Qt.Horizontal)
        self.sl_pwm3.setObjectName("sl_pwm3")
        self.sl_pwm2 = QtWidgets.QSlider(self.groupBox)
        self.sl_pwm2.setGeometry(QtCore.QRect(210, 90, 160, 20))
        self.sl_pwm2.setOrientation(QtCore.Qt.Horizontal)
        self.sl_pwm2.setObjectName("sl_pwm2")
        self.edit_duty2 = QtWidgets.QLineEdit(self.groupBox)
        self.edit_duty2.setGeometry(QtCore.QRect(70, 90, 71, 21))
        self.edit_duty2.setObjectName("edit_duty2")
        self.edit_duty3 = QtWidgets.QLineEdit(self.groupBox)
        self.edit_duty3.setGeometry(QtCore.QRect(70, 120, 71, 21))
        self.edit_duty3.setObjectName("edit_duty3")
        self.lockButton = QtWidgets.QRadioButton(self.groupBox)
        self.lockButton.setGeometry(QtCore.QRect(390, 90, 93, 20))
        self.lockButton.setObjectName("lockButton")
        self.edit_freq = QtWidgets.QLineEdit(self.groupBox)
        self.edit_freq.setGeometry(QtCore.QRect(70, 30, 71, 21))
        self.edit_freq.setObjectName("edit_freq")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 49, 16))
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(839, 30, 201, 21))
        self.comboBox.setObjectName("comboBox")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(200, 20, 571, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.f1Button = QtWidgets.QRadioButton(self.frame)
        self.f1Button.setGeometry(QtCore.QRect(190, 10, 93, 20))
        self.f1Button.setObjectName("f1Button")
        self.f10Button = QtWidgets.QRadioButton(self.frame)
        self.f10Button.setGeometry(QtCore.QRect(280, 10, 93, 20))
        self.f10Button.setObjectName("f10Button")
        self.freqSlider = QtWidgets.QSlider(self.frame)
        self.freqSlider.setGeometry(QtCore.QRect(10, 10, 160, 20))
        self.freqSlider.setMaximum(999)
        self.freqSlider.setOrientation(QtCore.Qt.Horizontal)
        self.freqSlider.setObjectName("freqSlider")
        self.f100Button = QtWidgets.QRadioButton(self.frame)
        self.f100Button.setGeometry(QtCore.QRect(370, 10, 93, 20))
        self.f100Button.setObjectName("f100Button")
        self.f1000Button = QtWidgets.QRadioButton(self.frame)
        self.f1000Button.setGeometry(QtCore.QRect(470, 10, 93, 20))
        self.f1000Button.setObjectName("f1000Button")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(150, 63, 49, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(150, 93, 49, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(150, 123, 49, 16))
        self.label_7.setObjectName("label_7")
        self.freqLabel = QtWidgets.QLabel(self.groupBox)
        self.freqLabel.setGeometry(QtCore.QRect(150, 33, 49, 16))
        self.freqLabel.setObjectName("freqLabel")
        self.verticalLayout_4.addWidget(self.groupBox)
        self.gridLayout.addLayout(self.verticalLayout_4, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1074, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionTest = QtWidgets.QAction(MainWindow)
        self.actionTest.setObjectName("actionTest")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PWM-Control"))
        self.groupBox.setTitle(_translate("MainWindow", "Control"))
        self.label.setText(_translate("MainWindow", "Duty 1:"))
        self.label_2.setText(_translate("MainWindow", "Duty 2:"))
        self.label_3.setText(_translate("MainWindow", "Duty 3:"))
        self.pb_Test.setText(_translate("MainWindow", "Exit"))
        self.lockButton.setText(_translate("MainWindow", "Lock"))
        self.label_4.setText(_translate("MainWindow", "Freq:"))
        self.f1Button.setText(_translate("MainWindow", "1 Hz"))
        self.f10Button.setText(_translate("MainWindow", "10 Hz"))
        self.f100Button.setText(_translate("MainWindow", "100 Hz"))
        self.f1000Button.setText(_translate("MainWindow", "1 KHz"))
        self.label_5.setText(_translate("MainWindow", "%"))
        self.label_6.setText(_translate("MainWindow", "%"))
        self.label_7.setText(_translate("MainWindow", "%"))
        self.freqLabel.setText(_translate("MainWindow", "Hz"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionTest.setText(_translate("MainWindow", "Test"))


from pyqtgraph import PlotWidget
